"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Point(google.protobuf.message.Message):
    """Points are represented as latitude-longitude pairs in the E7 representation
    (degrees multiplied by 10**7 and rounded to the nearest integer).
    Latitudes should be in the range +/- 90 degrees and longitude should be in
    the range +/- 180 degrees (inclusive).
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LATITUDE_FIELD_NUMBER: builtins.int
    LONGITUDE_FIELD_NUMBER: builtins.int
    latitude: builtins.int
    longitude: builtins.int
    def __init__(self,
        *,
        latitude: builtins.int = ...,
        longitude: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["latitude",b"latitude","longitude",b"longitude"]) -> None: ...
global___Point = Point

class RouteSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    POINT_COUNT_FIELD_NUMBER: builtins.int
    point_count: builtins.int
    """The number of points received."""

    def __init__(self,
        *,
        point_count: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["point_count",b"point_count"]) -> None: ...
global___RouteSummary = RouteSummary
